package cashtrack

import (
	greetv1 "cashtrack/backend/gen/greet/v1" // generated by protoc-gen-go
	"cashtrack/backend/gen/greet/v1/greetv1connect"
	"context"
	"fmt"
	"math/rand"

	"connectrpc.com/connect"
	"connectrpc.com/validate"
)

type GreetServer struct{}

type Greeting struct {
	Text     string
	Language string
}

var greetings = []Greeting{
	{Text: "Hello", Language: "English"},
	{Text: "Ola", Language: "Portuguese"},
	{Text: "Привет", Language: "Russian"},
	{Text: "Bonjour", Language: "French"},
	{Text: "Hola", Language: "Spanish"},
	{Text: "Ciao", Language: "Italian"},
	{Text: "Guten Tag", Language: "German"},
	{Text: "Salam", Language: "Arabic"},
	{Text: "Shalom", Language: "Hebrew"},
	{Text: "Namaste", Language: "Hindi"},
	{Text: "Konnichiwa", Language: "Japanese"},
	{Text: "Nǐ hǎo", Language: "Chinese (Mandarin)"},
	{Text: "Annyeonghaseyo", Language: "Korean"},
	{Text: "Merhaba", Language: "Turkish"},
	{Text: "Sawubona", Language: "Zulu"},
	{Text: "Habari", Language: "Swahili"},
	{Text: "Sveiki", Language: "Latvian"},
	{Text: "Tere", Language: "Estonian"},
	{Text: "Ahoj", Language: "Czech/Slovak"},
	{Text: "Zdravo", Language: "Serbian/Croatian/Bosnian"},
	{Text: "Selam", Language: "Amharic/Tigrinya/Turkish informal"},
	{Text: "Hej", Language: "Swedish"},
	{Text: "Hei", Language: "Norwegian"},
	{Text: "God dag", Language: "Danish/Norwegian"},
	{Text: "Dzień dobry", Language: "Polish"},
	{Text: "Yassas", Language: "Greek"},
	{Text: "Szia", Language: "Hungarian"},
	{Text: "Halo", Language: "Indonesian"},
	{Text: "Selamat siang", Language: "Indonesian (daytime)"},
	{Text: "Xin chào", Language: "Vietnamese"},
	{Text: "Shwmae", Language: "Welsh"},
	{Text: "Dia dhuit", Language: "Irish"},
	{Text: "Olá", Language: "Portuguese"},
	{Text: "Salut", Language: "Romanian/French informal"},
	{Text: "Sawasdee", Language: "Thai"},
	{Text: "Marhaba", Language: "Arabic (Levant/Gulf)"},
	{Text: "Sain baina uu", Language: "Mongolian"},
}

func NewGreetHandler() *Handler {
	greeter := new(GreetServer)

	path, handler := greetv1connect.NewGreetServiceHandler(
		greeter,
		// Validation via Protovalidate is almost always recommended
		connect.WithInterceptors(validate.NewInterceptor()),
	)
	return &Handler{Path: path, Handler: handler}
}

func (s *GreetServer) Greet(
	_ context.Context,
	req *greetv1.GreetRequest,
) (*greetv1.GreetResponse, error) {

	n := rand.Int() % len(greetings)
	res := &greetv1.GreetResponse{
		Greeting: fmt.Sprintf("%s, %s!", greetings[n].Text, req.Name),
		Language: greetings[n].Language,
	}

	return res, nil
}
