// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cashtrack

import (
	"context"
)

// Injectors from wire.go:

func InitializeApp(ctx context.Context) (*App, error) {
	config, err := ProvideConfig()
	if err != nil {
		return nil, err
	}
	serverConfig := config.ServerConfig
	dbConfig := config.Db
	pool, err := NewPgxPool(ctx, dbConfig)
	if err != nil {
		return nil, err
	}
	db, err := NewDB(pool)
	if err != nil {
		return nil, err
	}
	todoHandler := NewTodoHandler(db)
	greetHandler := NewGreetHandler()
	authHandler := NewAuthHandler(db)
	authServiceHandler := NewAuthServiceHandler(db)
	reportServiceHandler := NewReportServiceHandler(db)
	transactionsService := NewTransactionsService(db)
	transactionServiceHandler := NewTransactionServiceHandler(db, transactionsService)
	categoryServiceHandler := NewCategoryServiceHandler(db, transactionsService)
	v := handlers(todoHandler, greetHandler, authHandler, authServiceHandler, reportServiceHandler, transactionServiceHandler, categoryServiceHandler)
	server := NewHttpServer(serverConfig, v)
	reportParsingService := NewReportParsingService()
	reportProcessor := NewReportProcessor(db, reportParsingService, transactionsService)
	app := &App{
		Server:    server,
		Processor: reportProcessor,
	}
	return app, nil
}

// wire.go:

func handlers(
	todo *TodoHandler,
	greet *GreetHandler,
	auth *AuthHandler,
	authService *AuthServiceHandler,
	reportService *ReportServiceHandler,
	transactionService *TransactionServiceHandler,
	categoryService *CategoryServiceHandler,
) []*Handler {
	return []*Handler{
		(*Handler)(todo),
		(*Handler)(greet),
		(*Handler)(auth),
		(*Handler)(authService),
		(*Handler)(reportService),
		(*Handler)(transactionService),
		(*Handler)(categoryService),
	}
}
