// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cashtrack

import (
	"context"
	"net/http"
)

// Injectors from wire.go:

func InitializeHttpServer(ctx context.Context) (*http.Server, error) {
	config, err := ProvideConfig()
	if err != nil {
		return nil, err
	}
	serverConfig := config.ServerConfig
	dbConfig := config.Db
	pool, err := NewPgxPool(ctx, dbConfig)
	if err != nil {
		return nil, err
	}
	db, err := NewDB(pool)
	if err != nil {
		return nil, err
	}
	todoHandler := NewTodoHandler(db)
	greetHandler := NewGreetHandler()
	authHandler := NewAuthHandler(db)
	authMeHandler := NewAuthMeHandler(db)
	v := handlers(todoHandler, greetHandler, authHandler, authMeHandler)
	server := NewHttpServer(serverConfig, v)
	return server, nil
}

// wire.go:

func handlers(todo *TodoHandler, greet *GreetHandler, auth *AuthHandler, authMe *AuthMeHandler) []*Handler {
	return []*Handler{(*Handler)(todo), (*Handler)(greet), (*Handler)(auth), (*Handler)(authMe)}
}
