// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cashtrack

import (
	"context"
	"net/http"
)

// Injectors from wire.go:

func InitializeApp(ctx context.Context) (*http.Server, *ReportProcessor, error) {
	config, err := ProvideConfig()
	if err != nil {
		return nil, nil, err
	}
	serverConfig := config.ServerConfig
	dbConfig := config.Db
	pool, err := NewPgxPool(ctx, dbConfig)
	if err != nil {
		return nil, nil, err
	}
	db, err := NewDB(pool)
	if err != nil {
		return nil, nil, err
	}
	todoHandler := NewTodoHandler(db)
	greetHandler := NewGreetHandler()
	authHandler := NewAuthHandler(db)
	authMeHandler := NewAuthMeHandler(db)
	authLogoutHandler := NewAuthLogoutHandler(db)
	reportUploadHandler := NewReportUploadHandler(db)
	reportListHandler := NewReportListHandler(db)
	reportDownloadHandler := NewReportDownloadHandler(db)
	reportDeleteHandler := NewReportDeleteHandler(db)
	v := handlers(todoHandler, greetHandler, authHandler, authMeHandler, authLogoutHandler, reportUploadHandler, reportListHandler, reportDownloadHandler, reportDeleteHandler)
	server := NewHttpServer(serverConfig, v)
	reportParsingService := NewReportParsingService()
	transactionsService := NewTransactionsService(db)
	reportProcessor := NewReportProcessor(db, reportParsingService, transactionsService)
	return server, reportProcessor, nil
}

// wire.go:

func handlers(todo *TodoHandler, greet *GreetHandler, auth *AuthHandler, authMe *AuthMeHandler, authLogout *AuthLogoutHandler, upload *ReportUploadHandler, reportList *ReportListHandler, reportDownload *ReportDownloadHandler, reportDelete *ReportDeleteHandler) []*Handler {
	return []*Handler{(*Handler)(todo), (*Handler)(greet), (*Handler)(auth), (*Handler)(authMe), (*Handler)(authLogout), (*Handler)(upload), (*Handler)(reportList), (*Handler)(reportDownload), (*Handler)(reportDelete)}
}
