package server

import (
	greetv1 "cashtrack/gen/greet/v1" // generated by protoc-gen-go
	"context"
	"fmt"
	"math/rand"
)

type GreetServer struct{}

var greatings = []string{"Hello", "Ola", "Привет"}

func (s *GreetServer) Greet(
	_ context.Context,
	req *greetv1.GreetRequest,
) (*greetv1.GreetResponse, error) {

	n := rand.Int() % len(greatings)
	res := &greetv1.GreetResponse{
		Greeting: fmt.Sprintf("%s, %s!", greatings[n], req.Name),
	}

	return res, nil
}
