package server

import (
	greetv1 "cashtrack/gen/greet/v1" // generated by protoc-gen-go
	"context"
	"fmt"
)

type GreetServer struct{}

func (s *GreetServer) Greet(
	_ context.Context,
	req *greetv1.GreetRequest,
) (*greetv1.GreetResponse, error) {
	res := &greetv1.GreetResponse{
		Greeting: fmt.Sprintf("Hello, %s!", req.Name),
	}

	return res, nil
}
