package cashtrack

import (
	greetv1 "cashtrack/server/gen/greet/v1" // generated by protoc-gen-go
	"cashtrack/server/gen/greet/v1/greetv1connect"
	"context"
	"fmt"
	"math/rand"

	"connectrpc.com/connect"
	"connectrpc.com/validate"
)

type GreetServer struct{}

var greatings = []string{
	"Hello",
	"Ola",
	"Привет",
	"Bonjour",
	"Hola",
	"Ciao",
	"Guten Tag",
	"Salam",
	"Shalom",
	"Namaste",
	"Konnichiwa",
	"Nǐ hǎo",
	"Annyeonghaseyo",
	"Merhaba",
	"Sawubona",
	"Habari",
	"Sveiki",
	"Tere",
	"Ahoj",
	"Zdravo",
	"Selam",
	"Hej",
	"Hei",
	"God dag",
	"Dzień dobry",
	"Yassas",
	"Szia",
	"Halo",
	"Selamat siang",
	"Xin chào",
	"Halo",
	"Shwmae",
	"Dia dhuit",
	"Olá",
	"Salut",
	"Sawasdee",
	"Marhaba",
	"Sain baina uu",
}

func NewGreetHandler() *Handler {
	greeter := new(GreetServer)

	path, handler := greetv1connect.NewGreetServiceHandler(
		greeter,
		// Validation via Protovalidate is almost always recommended
		connect.WithInterceptors(validate.NewInterceptor()),
	)
	return &Handler{Path: path, Handler: handler}
}

func (s *GreetServer) Greet(
	_ context.Context,
	req *greetv1.GreetRequest,
) (*greetv1.GreetResponse, error) {

	n := rand.Int() % len(greatings)
	res := &greetv1.GreetResponse{
		Greeting: fmt.Sprintf("%s, %s!", greatings[n], req.Name),
	}

	return res, nil
}
