-- Generated by "make generate". DO NOT EDIT.
CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA public;
CREATE TABLE public.categories (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    name character varying(255) NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    color character varying(7),
    parent_id bigint,
    is_group boolean DEFAULT false NOT NULL
);
CREATE SEQUENCE public.categories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE public.categories_id_seq OWNED BY public.categories.id;
CREATE TABLE public.category_rules (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    category_id bigint NOT NULL,
    description_contains text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    "position" integer NOT NULL
);
CREATE SEQUENCE public.category_rules_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE public.category_rules_id_seq OWNED BY public.category_rules.id;
CREATE TABLE public.exchange_rates (
    id bigint NOT NULL,
    rate_date date NOT NULL,
    base_currency character varying(3) NOT NULL,
    target_currency character varying(3) NOT NULL,
    rate numeric(18,8) NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE SEQUENCE public.exchange_rates_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE public.exchange_rates_id_seq OWNED BY public.exchange_rates.id;
CREATE TABLE public.financial_reports (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    filename character varying(255) NOT NULL,
    content_type character varying(255),
    data bytea NOT NULL,
    uploaded_at timestamp with time zone DEFAULT now() NOT NULL,
    status character varying(32) DEFAULT 'pending'::character varying NOT NULL,
    status_description text
);
CREATE SEQUENCE public.financial_reports_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE public.financial_reports_id_seq OWNED BY public.financial_reports.id;
CREATE TABLE public.sessions (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    user_id integer,
    expires timestamp with time zone NOT NULL
);
CREATE TABLE public.todo (
    id integer NOT NULL,
    title character varying(255) NOT NULL,
    user_id integer NOT NULL
);
CREATE SEQUENCE public.todo_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE public.todo_id_seq OWNED BY public.todo.id;
CREATE TABLE public.transactions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    source_file_id bigint NOT NULL,
    source_file_row integer NOT NULL,
    parser_name character varying(64) NOT NULL,
    posted_date date NOT NULL,
    description text NOT NULL,
    amount numeric(18,2) NOT NULL,
    currency character varying(3) NOT NULL,
    transaction_id text,
    entry_type character varying(16) NOT NULL,
    source_account_number character varying(64),
    source_card_number character varying(64),
    parser_meta jsonb,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    category_id bigint,
    category_source text,
    CONSTRAINT transactions_category_source_check CHECK (((category_source = ANY (ARRAY['manual'::text, 'rule'::text])) OR (category_source IS NULL)))
);
CREATE SEQUENCE public.transactions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE public.transactions_id_seq OWNED BY public.transactions.id;
CREATE TABLE public.users (
    id integer NOT NULL,
    username character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    language character varying(10) DEFAULT 'en'::character varying NOT NULL
);
ALTER TABLE public.users ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
ALTER TABLE ONLY public.categories ALTER COLUMN id SET DEFAULT nextval('public.categories_id_seq'::regclass);
ALTER TABLE ONLY public.category_rules ALTER COLUMN id SET DEFAULT nextval('public.category_rules_id_seq'::regclass);
ALTER TABLE ONLY public.exchange_rates ALTER COLUMN id SET DEFAULT nextval('public.exchange_rates_id_seq'::regclass);
ALTER TABLE ONLY public.financial_reports ALTER COLUMN id SET DEFAULT nextval('public.financial_reports_id_seq'::regclass);
ALTER TABLE ONLY public.todo ALTER COLUMN id SET DEFAULT nextval('public.todo_id_seq'::regclass);
ALTER TABLE ONLY public.transactions ALTER COLUMN id SET DEFAULT nextval('public.transactions_id_seq'::regclass);
ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.category_rules
    ADD CONSTRAINT category_rules_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.exchange_rates
    ADD CONSTRAINT exchange_rates_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.financial_reports
    ADD CONSTRAINT financial_reports_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.sessions
    ADD CONSTRAINT sessions_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.todo
    ADD CONSTRAINT todo_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT transactions_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_username_key UNIQUE (username);
CREATE INDEX categories_user_id_idx ON public.categories USING btree (user_id);
CREATE INDEX categories_parent_id_idx ON public.categories USING btree (parent_id);
CREATE INDEX category_rules_category_id_idx ON public.category_rules USING btree (category_id);
CREATE INDEX category_rules_user_id_idx ON public.category_rules USING btree (user_id);
CREATE INDEX category_rules_user_position_idx ON public.category_rules USING btree (user_id, "position");
CREATE UNIQUE INDEX exchange_rates_unique_idx ON public.exchange_rates USING btree (rate_date, base_currency, target_currency);
CREATE INDEX financial_reports_user_id_idx ON public.financial_reports USING btree (user_id);
CREATE INDEX todo_user_id_idx ON public.todo USING btree (user_id);
CREATE INDEX transactions_category_id_idx ON public.transactions USING btree (category_id);
CREATE INDEX transactions_description_tsv_idx ON public.transactions USING gin (to_tsvector('simple'::regconfig, description));
CREATE INDEX transactions_entry_type_idx ON public.transactions USING btree (entry_type);
CREATE INDEX transactions_posted_date_idx ON public.transactions USING btree (posted_date);
CREATE INDEX transactions_source_account_number_idx ON public.transactions USING btree (source_account_number);
CREATE INDEX transactions_source_card_number_idx ON public.transactions USING btree (source_card_number);
CREATE INDEX transactions_source_file_id_idx ON public.transactions USING btree (source_file_id);
CREATE INDEX transactions_user_id_idx ON public.transactions USING btree (user_id);
CREATE UNIQUE INDEX users_username_idx ON public.users USING btree (username);
ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.categories(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.category_rules
    ADD CONSTRAINT category_rules_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.categories(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.category_rules
    ADD CONSTRAINT category_rules_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.financial_reports
    ADD CONSTRAINT financial_reports_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.sessions
    ADD CONSTRAINT sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.todo
    ADD CONSTRAINT todo_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT transactions_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.categories(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT transactions_source_file_id_fkey FOREIGN KEY (source_file_id) REFERENCES public.financial_reports(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT transactions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;
