package main

import (
	"net/http"

	"cashtrack/gen/greet/v1/greetv1connect" // generated by protoc-gen-connect-go
	"cashtrack/server"

	"connectrpc.com/connect"
	"connectrpc.com/validate"
)

func main() {
	greeter := &server.GreetServer{}
	mux := http.NewServeMux()
	path, handler := greetv1connect.NewGreetServiceHandler(
		greeter,
		// Validation via Protovalidate is almost always recommended
		connect.WithInterceptors(validate.NewInterceptor()),
	)
	mux.Handle(path, handler)
	p := new(http.Protocols)
	p.SetHTTP1(true)
	// Use h2c so we can serve HTTP/2 without TLS.
	p.SetUnencryptedHTTP2(true)
	s := http.Server{
		Addr:      "localhost:8080",
		Handler:   mux,
		Protocols: p,
	}
	s.ListenAndServe()
}
